FROM python:3.12-slim

# Install required system packages for OpenCV and YOLO
RUN apt-get update && \
    apt-get install -y libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 1234

CMD ["python", "src/main.py"]